force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Days_Until_Insurance_s_End__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Insurance_s_End__c</fullName>
    <label>Days Until Insurance&apos;s End</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Days_Until_Next_Car_Review__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Next_Car_Review__c</fullName>
    <label>Days Until Next Car Review</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CarTriggerHandlerTests.cls
@isTest
public with sharing class CarTriggerHandlerTests {
    @isTest
    private static void shouldCalculateDaysUntilInsuranceExpiryDateAndCarReview(){

        Date lastCarReviewDate = date.newInstance(2020, 7, 13);
        Date insuranceEndDate = date.newInstance(2021, 8, 13);

        List<Car__c> carsToAdd = TestDataFactory.createCars(10, 2005, lastCarReviewDate, insuranceEndDate, 100000, 50000);

        System.Test.startTest();
                List<Database.SaveResult> results = Database.insert(carsToAdd, false);
        System.Test.stopTest();
        
        Integer daysUntilNextCarReview = System.today().daysBetween(lastCarReviewDate.addYears(1));
        Integer daysUntilInsuraceEnd = System.today().daysBetween(insuranceEndDate);

        System.assertEquals(10, [SELECT COUNT() FROM Car__c WHERE Days_Until_Next_Car_Review__c = :daysUntilNextCarReview AND Days_Until_Insurance_s_End__c = :daysUntilInsuraceEnd]);
    }
}