force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Insurance_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiry_Date__c</fullName>
    <label>Insurance Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Last_Car_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Car_Review_Date__c</fullName>
    <label>Last Car Review Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Mileage_When_Last_Timing_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Mileage_When_Last_Timing_Replacement__c</fullName>
    <label>Mileage When Last Timing Replacement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Production_Year__c.field-meta.xml
<CustomField>
    <fullName>Production_Year__c</fullName>
    <label>Production Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Need a repair</fullName>
            </value>
            <value>
                <fullName>Need a review</fullName>
            </value>
            <value>
                <fullName>Probably dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <label>Repair</label>
    <nameField>
        <label>Repair Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repairs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Repairs</relationshipLabel>
    <relationshipName>Repairs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To do</fullName>
                <default>true</default>
                <label>To do</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Car__c> createCars(Integer numberOfCarsToCreate, Integer productionYear, Date lastCarReviewDate, Date insuranceExpiryDate, Integer mileage, Integer lastTimingReplacementMileage){
        List<Car__c> carsToCreate = new List<Car__c>();

        for(Integer i=0; i<numberOfCarsToCreate; i++){
                carsToCreate.add(new Car__c(Production_Year__c = productionYear, Last_Car_Review_Date__c=lastCarReviewDate,
                Insurance_Expiry_Date__c = insuranceExpiryDate, Mileage__c = mileage, Mileage_When_Last_Timing_Replacement__c = lastTimingReplacementMileage));   
        }
        return carsToCreate;

    }

    public static List<Repair__c> createRepairs(Integer numberOfRepairs, Id carId, String status, String reason, Integer cost){
        List<Repair__c> repairsToCreate = new List<Repair__c>();

        for(Integer i=0; i<numberOfRepairs; i++){
            repairsToCreate.add(new Repair__c(Name='repairName ' + i, Car__c=carId, Status__c=status, Reason__c=reason, Cost__c=cost));
        }
        return repairsToCreate;
    }

    public static List<Repair__c> changeRepairsStatusToInProgress(List<Repair__c> repairsToUpdate){
        for(Repair__c repair : repairsToUpdate){
            repair.Status__c = 'In progress';
        }
        return repairsToUpdate;
    }

}