force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Days_Until_Insurance_s_End__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Insurance_s_End__c</fullName>
    <label>Days Until Insurance&apos;s End</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Days_Until_Next_Car_Review__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Next_Car_Review__c</fullName>
    <label>Days Until Next Car Review</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Insurance_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiry_Date__c</fullName>
    <label>Insurance Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Last_Car_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Car_Review_Date__c</fullName>
    <label>Last Car Review Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Production_Year__c.field-meta.xml
<CustomField>
    <fullName>Production_Year__c</fullName>
    <label>Production Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CarTriggerTests.cls
@isTest
public with sharing class CarTriggerTests {

    @isTest
    private static void shouldCalculateDaysUntilInsuranceExpiryAndCarReview(){

        List<Car__c> carsToAdd = new List<Car__c>();
        Date carReview = date.newInstance(2020, 7, 13);
        Date insuranceEnd = date.newInstance(2021, 8, 13);

        for(Integer i=0; i<10; i++){
    
            carsToAdd.add(new Car__c(Name='car ' + i, Production_Year__c=2005, Last_Car_Review_Date__c=carReview,
                                Insurance_Expiry_Date__c = insuranceEnd, Mileage__c=100000));
    
        }
        
        System.Test.startTest();
            List<Database.SaveResult> results = Database.insert(carsToAdd, false);
        System.Test.stopTest();
        
        Integer daysUntilCarReview = System.today().daysBetween(carReview.addYears(1));
        Integer daysUntilInsuraceEnd = System.today().daysBetween(insuranceEnd);

        for(Database.SaveResult res : results){
            System.assert(res.isSuccess());
        }
        
        System.assertEquals(10, [SELECT COUNT() FROM Car__c WHERE Days_Until_Next_Car_Review__c = :daysUntilCarReview AND Days_Until_Insurance_s_End__c = :daysUntilInsuraceEnd]);
    }
}