force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Days_Until_Insurance_s_End__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Insurance_s_End__c</fullName>
    <label>Days Until Insurance&apos;s End</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Days_Until_Next_Car_Review__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Next_Car_Review__c</fullName>
    <label>Days Until Next Car Review</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Does_Need_Timing_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Does_Need_Timing_Replacement__c</fullName>
    <formula>IF( Mileage__c -  Mileage_When_Last_Timing_Replacement__c &gt; 120000, &apos;ZDECYDOWANIE TAK&apos;, 
	IF(Mileage__c -  Mileage_When_Last_Timing_Replacement__c &gt; 85000, &apos;TAK&apos;, &apos;NIE&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Does Need Timing Replacement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Insurance_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiry_Date__c</fullName>
    <label>Insurance Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Last_Car_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Car_Review_Date__c</fullName>
    <label>Last Car Review Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Need a repair</fullName>
            </value>
            <value>
                <fullName>Need a review</fullName>
            </value>
            <value>
                <fullName>Probably dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarUpdateBatch.cls
public class CarUpdateBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, Days_Until_Insurance_s_End__c, Days_Until_Next_Car_Review__c, ' + 
                                    'Does_Need_Timing_Replacement__c, Last_Car_Review_Date__c, Insurance_Expiry_Date__c, Status__c FROM Car__c');
    }

    public static void execute(Database.BatchableContext bc, List<Car__c> scope){
        List<Car__c> carsToUpdate = new List<Car__c>();

        for(Car__c car : scope){
            car.Days_Until_Next_Car_Review__c = System.today().daysBetween(car.Last_Car_Review_Date__c.addYears(1));
            car.Days_Until_Insurance_s_End__c = System.today().daysBetween(car.Insurance_Expiry_Date__c);

            if(car.Days_Until_Insurance_s_End__c <= 0 && car.Does_Need_Timing_Replacement__c == 'ZDECYDOWANIE TAK'){
                car.Status__c = 'Probably dead';
            }
            else if(car.Does_Need_Timing_Replacement__c == 'ZDECYDOWANIE TAK'){
                car.Status__c = 'Need a repair';
            }
            else if(car.Days_Until_Insurance_s_End__c <= 0){
                car.Status__c = 'Need a review';
            }

            System.debug('yyyy ' + car.Status__c);
            carsToUpdate.add(car);
        }
        update carsToUpdate;
    }

    public static void finish(Database.BatchableContext bc){}
}